### PR TITLE
Actions for building image & tagging release

### PR DESCRIPTION
**Pull request by aelkiss**
Will squash this but wanted to get a draft PR up for review.

### CODE REVIEW

**Comment by aelkiss** [comment]
FYI @niquerio

**Comment by aelkiss** [comment]
Ready for review; I tested locally with act and minikube.

**Comment by aelkiss** [comment]
- Need to update the main README

**Review by moseshll — APPROVED** [review]
workflow-dispatch -> workflow_dispatch change in README as noted. I like the inclusion of sane defaults.

**Comment by aelkiss** [comment]
FYI @daaang

**Pull request merged**
